name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print hellow
        run: echo "Hello World"
      - name: Print bye
        run: echo "Done - Bye!"
      - name: Print new step
        run: echo "this is brand new step"